In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.3.3'

In [3]:
df = pd.read_excel(r'D:\NIT\1. NIT_Batches\2. EVENING BATCH\N_Batch -- 6.00PM-- Jan 27\2. Sep\31st - Pandas\Country GDP Analysis- project\data.xlsx')

In [ ]:
#!pip install openpyxl

In [4]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [5]:
df.shape # rows & column from the dataframe

(195, 5)

In [6]:
len(df)

195

In [7]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [8]:
len(df.columns)

5

In [9]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [10]:
df.isnull()

     CountryName  CountryCode  BirthRate  InternetUsers  IncomeGroup
0          False        False      False          False        False
1          False        False      False          False        False
2          False        False      False          False        False
3          False        False      False          False        False
4          False        False      False          False        False
..           ...          ...        ...            ...          ...
190        False        False      False          False        False
191        False        False      False          False        False
192        False        False      False          False        False
193        False        False      False          False        False
194        False        False      False          False        False

[195 rows x 5 columns]

In [11]:
df.isnull().sum()

CountryName      0
CountryCode      0
BirthRate        0
InternetUsers    0
IncomeGroup      0
dtype: int64

In [12]:
df.isna().sum()

CountryName      0
CountryCode      0
BirthRate        0
InternetUsers    0
IncomeGroup      0
dtype: int64

In [14]:
type(df)

pandas.core.frame.DataFrame

In [13]:
df.info() #information of the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CountryName    195 non-null    object
 1   CountryCode    195 non-null    object
 2   BirthRate      195 non-null    float64
 3   InternetUsers  195 non-null    float64
 4   IncomeGroup    195 non-null    object
dtypes: float64(2), object(3)
memory usage: 7.7+ KB

In [15]:
df.head()

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income

In [19]:
df.head(10)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9000,High income
1,Afghanistan,AFG,35.253,5.9000,Low income
2,Angola,AGO,45.985,19.1000,Upper middle income
3,Albania,ALB,12.877,57.2000,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0000,High income
5,Argentina,ARG,17.716,59.9000,High income
6,Armenia,ARM,13.308,41.9000,Lower middle income
7,Antigua and Barbuda,ATG,16.447,63.4000,High income
8,Australia,AUS,13.200,83.0000,High income
9,Austria,AUT,9.400,80.6188,High income

In [20]:
df.tail()

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [21]:
df.tail(2)

    CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
193      Zambia         ZMB     40.471           15.4  Lower middle income
194    Zimbabwe         ZWE     35.715           18.5           Low income

In [23]:
df[:] # slicing in pandas

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [24]:
df[10:20]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
10,Azerbaijan,AZE,18.300,58.70000,Upper middle income
11,Burundi,BDI,44.151,1.30000,Low income
12,Belgium,BEL,11.200,82.17020,High income
13,Benin,BEN,36.440,4.90000,Low income
14,Burkina Faso,BFA,40.551,9.10000,Low income
15,Bangladesh,BGD,20.142,6.63000,Lower middle income
16,Bulgaria,BGR,9.200,53.06150,Upper middle income
17,Bahrain,BHR,15.040,90.00004,High income
18,"Bahamas, The",BHS,15.339,72.00000,High income
19,Bosnia and Herzegovina,BIH,9.062,57.79000,Upper middle income

In [25]:
df[::-1]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
194,Zimbabwe,ZWE,35.715,18.5,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
191,South Africa,ZAF,20.850,46.5,Upper middle income
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
...,...,...,...,...,...
4,United Arab Emirates,ARE,11.044,88.0,High income
3,Albania,ALB,12.877,57.2,Upper middle income
2,Angola,AGO,45.985,19.1,Upper middle income
1,Afghanistan,AFG,35.253,5.9,Low income
0,Aruba,ABW,10.244,78.9,High income

In [26]:
df[0:200:15]

    CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0         Aruba         ABW     10.244        78.9000          High income
15   Bangladesh         BGD     20.142         6.6300  Lower middle income
30       Canada         CAN     10.900        85.8000          High income
45      Germany         DEU      8.500        84.1700          High income
60        Gabon         GAB     30.555         9.2000  Upper middle income
75     Honduras         HND     21.593        17.8000  Lower middle income
90   Kazakhstan         KAZ     22.730        54.0000  Upper middle income
105   Lithuania         LTU     10.100        68.4529          High income
120  Mozambique         MOZ     39.705         5.4000           Low income
135    Pakistan         PAK     29.582        10.9000  Lower middle income
150       Sudan         SDN     33.477        22.7000  Lower middle income
165  Seychelles         SYC     18.600        50.4000          High income
180     Uruguay         URY     14.374        57.6900          High income

In [27]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [28]:
df['CountryName']

0                     Aruba
1               Afghanistan
2                    Angola
3                   Albania
4      United Arab Emirates
               ...
190             Yemen, Rep.
191            South Africa
192        Congo, Dem. Rep.
193                  Zambia
194                Zimbabwe
Name: CountryName, Length: 195, dtype: object

In [29]:
df['CountryCode']

0      ABW
1      AFG
2      AGO
3      ALB
4      ARE
      ...
190    YEM
191    ZAF
192    COD
193    ZMB
194    ZWE
Name: CountryCode, Length: 195, dtype: object

In [31]:
df[['CountryName', 'CountryCode']]

              CountryName CountryCode
0                   Aruba         ABW
1             Afghanistan         AFG
2                  Angola         AGO
3                 Albania         ALB
4    United Arab Emirates         ARE
..                    ...         ...
190           Yemen, Rep.         YEM
191          South Africa         ZAF
192      Congo, Dem. Rep.         COD
193                Zambia         ZMB
194              Zimbabwe         ZWE

[195 rows x 2 columns]

In [32]:
# divide the dataset into categorical & numerical

In [33]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [34]:
df.head(1)

  CountryName CountryCode  BirthRate  InternetUsers  IncomeGroup
0       Aruba         ABW     10.244           78.9  High income

In [35]:
df_cat = df[['CountryName', 'CountryCode', 'IncomeGroup']]
df_cat

              CountryName CountryCode          IncomeGroup
0                   Aruba         ABW          High income
1             Afghanistan         AFG           Low income
2                  Angola         AGO  Upper middle income
3                 Albania         ALB  Upper middle income
4    United Arab Emirates         ARE          High income
..                    ...         ...                  ...
190           Yemen, Rep.         YEM  Lower middle income
191          South Africa         ZAF  Upper middle income
192      Congo, Dem. Rep.         COD           Low income
193                Zambia         ZMB  Lower middle income
194              Zimbabwe         ZWE           Low income

[195 rows x 3 columns]

In [38]:
df_num = df[['BirthRate','InternetUsers']]
df_num

     BirthRate  InternetUsers
0       10.244           78.9
1       35.253            5.9
2       45.985           19.1
3       12.877           57.2
4       11.044           88.0
..         ...            ...
190     32.947           20.0
191     20.850           46.5
192     42.394            2.2
193     40.471           15.4
194     35.715           18.5

[195 rows x 2 columns]

In [40]:
print(len(df.columns)) 
print(len(df_cat.columns)) 
print(len(df_num.columns))

5
3
2

In [42]:
print(df.shape)
print(df_cat.shape) 
print(df_num.shape)

(195, 5)
(195, 3)
(195, 2)

In [43]:
df.describe()

        BirthRate  InternetUsers
count  195.000000     195.000000
mean    21.469928      42.076471
std     10.605467      29.030788
min      7.900000       0.900000
25%     12.120500      14.520000
50%     19.680000      41.000000
75%     29.759500      66.225000
max     49.661000      96.546800

In [45]:
df_cat.head()

            CountryName CountryCode          IncomeGroup
0                 Aruba         ABW          High income
1           Afghanistan         AFG           Low income
2                Angola         AGO  Upper middle income
3               Albania         ALB  Upper middle income
4  United Arab Emirates         ARE          High income

In [46]:
df_cat.describe()

       CountryName CountryCode  IncomeGroup
count          195         195          195
unique         195         195            4
top          Aruba         ABW  High income
freq             1           1           67

In [47]:
df_num.describe()

        BirthRate  InternetUsers
count  195.000000     195.000000
mean    21.469928      42.076471
std     10.605467      29.030788
min      7.900000       0.900000
25%     12.120500      14.520000
50%     19.680000      41.000000
75%     29.759500      66.225000
max     49.661000      96.546800

In [48]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [49]:
df.columns = ['a','b','c','d','e']

In [50]:
df.columns

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [53]:
df.columns = ['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers', 'IncomeGroup']

In [55]:
df.head(1)

  CountryName CountryCode  BirthRate  InternetUsers  IncomeGroup
0       Aruba         ABW     10.244           78.9  High income

In [56]:
df.BirthRate * df.InternetUsers

0      808.2516
1      207.9927
2      878.3135
3      736.5644
4      971.8720
         ...
190    658.9400
191    969.5250
192     93.2668
193    623.2534
194    660.7275
Length: 195, dtype: float64

In [57]:
df['myCalc'] = df.BirthRate * df.InternetUsers

In [58]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup', 'myCalc'],
      dtype='object')

In [60]:
df.head()

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup,myCalc
0,Aruba,ABW,10.244,78.9,High income,808.2516
1,Afghanistan,AFG,35.253,5.9,Low income,207.9927
2,Angola,AGO,45.985,19.1,Upper middle income,878.3135
3,Albania,ALB,12.877,57.2,Upper middle income,736.5644
4,United Arab Emirates,ARE,11.044,88.0,High income,971.8720

In [61]:
df = df.drop('myCalc',axis = 0)

# axis - 0 -- pandas automatically detects its row part 
# axis-1 -- pandas automatiec detect it columns

KeyError: "['myCalc'] not found in axis"

In [62]:
df = df.drop('myCalc',axis = 1)

In [63]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [64]:
df['IncomeGroup']

0              High income
1               Low income
2      Upper middle income
3      Upper middle income
4              High income
              ...
190    Lower middle income
191    Upper middle income
192             Low income
193    Lower middle income
194             Low income
Name: IncomeGroup, Length: 195, dtype: object

In [66]:
df[df.IncomeGroup == 'Low income']

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
1,Afghanistan,AFG,35.253,5.90,Low income
11,Burundi,BDI,44.151,1.30,Low income
13,Benin,BEN,36.440,4.90,Low income
14,Burkina Faso,BFA,40.551,9.10,Low income
29,Central African Republic,CAF,34.076,3.50,Low income
38,Comoros,COM,34.326,6.50,Low income
52,Eritrea,ERI,34.800,0.90,Low income
55,Ethiopia,ETH,32.925,1.90,Low income
64,Guinea,GIN,37.337,1.60,Low income
65,"Gambia, The",GMB,42.525,14.00,Low income
66,Guinea-Bissau,GNB,37.503,3.10,Low income
77,Haiti,HTI,25.345,10.60,Low income
93,Cambodia,KHM,24.462,6.80,Low income
99,Liberia,LBR,35.521,3.20,Low income
111,Madagascar,MDG,34.686,3.00,Low income
115,Mali,MLI,44.138,3.50,Low income
120,Mozambique,MOZ,39.705,5.40,Low income
123,Malawi,MWI,39.459,5.05,Low income
127,Niger,NER,49.661,1.70,Low income
132,Nepal,NPL,20.923,13.30,Low income
148,Rwanda,RWA,32.689,9.00,Low income
154,Sierra Leone,SLE,36.729,1.70,Low income
156,Somalia,SOM,43.891,1.50,Low income
158,South Sudan,SSD,37.126,14.10,Low income
167,Chad,TCD,45.745,2.30,Low income
168,Togo,TGO,36.080,4.50,Low income
177,Tanzania,TZA,39.518,4.40,Low income
178,Uganda,UGA,43.474,16.20,Low income
192,"Congo, Dem. Rep.",COD,42.394,2.20,Low income
194,Zimbabwe,ZWE,35.715,18.50,Low income

In [68]:
df['IncomeGroup'].unique()

array(['High income', 'Low income', 'Upper middle income',
       'Lower middle income'], dtype=object)

In [69]:
df['IncomeGroup'].nunique()

4

In [ ]:
# we will next concept tomorrow 
# i will very repo 
# what every your question please 
# machine learning